---
title: "Getting started"
author: "NEST CoreDev Team"
date: "03.04.2022"
output:
  rmarkdown::html_document:
    theme: "spacelab"
    highlight: "kate"
    toc: true
    toc_float: true
vignette: >
  %\VignetteIndexEntry{Getting started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
### Introduction
`teal.modules.clinical` is an R library implementing a number of `teal` modules helpful for exploring clinical
trials data, specifically targeted at data in the `ADaM` standard. `teal.modules.clinical` modules can be used
with data other than clinical data in the `ADaM` standard but some features of the package will make little sense then.

It is highly recommended to read the `README` file and the introductory vignette for the `teal` library itself
before continuing with this vignette. The concepts presented here require knowledge about the core features of `teal`,
specifically on how to launch a `teal` application and how to pass data into it. A good starting point is
[`teal's README`](https://github.com/insightsengineering/teal).

You can read more about `ADaM` [here](https://www.cdisc.org/standards/foundational/adam).
### Main features
The package provides ready-to-use `teal` modules you can embed in your `teal` application. The modules
generate highly customizable tables, plots and outputs often used in exploratory data analysis, e.g.:
* `ANCOVA` - `tm_t_ancova()`
* a binary outcome response table - `tm_t_binary_outcome()`
* Cox regression - `tm_t_coxreg()`
* a summary of adverse events - `tm_t_events_summary()`
* logistic regression - `tm_t_logistic()`
* `SMQ` table - `tm_t_smq()`
* a `time to event` table - `tm_t_tte()`
* a bar chart - `tm_g_barchart_simple()`
* a confidence interval plot - `tm_g_ci()`
* Kaplan-Meier plot - `tm_g_km()`

The library also offers a group of patient profile modules targeted for clinical statisticians and physicians
who want to review data on a per patient basis. The modules present data about patient's adverse events,
their severity, the current therapy, their laboratory results and more.

### A simple application
You need to embed a module inside a shiny application to interact with it. In case of `teal.modules.clinical`,
we recommend launching the modules using `teal` because `teal.modules.clinical` does not provide launching capabilities on its own.

A simple application including a bar chart module could look like this:
```r
library(teal.modules.clinical)
library(scda)

ADSL <- synthetic_cdisc_data("latest")$adsl
ADAE <- synthetic_cdisc_data("latest")$adae

app <- teal::init(
  data = teal::cdisc_data(
    teal::cdisc_dataset("ADSL", ADSL, code = "ADSL <- synthetic_cdisc_data('latest')$adsl"),
    teal::cdisc_dataset("ADAE", ADAE, code = "ADAE <- synthetic_cdisc_data('latest')$adae"),
    check = FALSE
  ),
  modules = list(tm_g_barchart_simple(label = "ADAE Analysis", x = ::data_extract_spec(
    dataname = "ADSL",
    select = ::select_spec(choices = ::variable_choices(ADSL), multiple = FALSE)
  )))
)

if (interactive()) shiny::shinyApp(app$ui, app$server)
```

Most of the functions used in the example come from `teal`, not `teal.modules.clinical`. As pointed out,
`teal.modules.clinical` exports modules and needs support from other libraries to flesh out its functionality. Actually,
the only function from `teal.modules.clinical` in this example is `tm_g_barchart_simple`.

Let's break it down:
```r
library(teal.modules.clinical)
library(scda)
```
The above lines load the libraries used in this example. `scda` is a package containing sample data in the `ADaM`
format. We use `scda` to load data into two R objects:
```r
ADSL <- synthetic_cdisc_data("latest")$adsl
ADAE <- synthetic_cdisc_data("latest")$adae
```

In the next step, we use `teal` to create `shiny` `ui` and `server` functions we can launch using `shiny`. The `data`
argument tells `teal` about the input data - the two `ADaM` datasets we have prepared beforehand and the `modules`
argument indicates what modules we want included in the application. This time we include only one - `tm_g_barchart_simple`.
```r
app <- teal::init(
  data = teal::cdisc_data(
    teal::cdisc_dataset("ADSL", ADSL, code = "ADSL <- synthetic_cdisc_data('latest')$adsl"),
    teal::cdisc_dataset("ADAE", ADAE, code = "ADAE <- synthetic_cdisc_data('latest')$adae"),
    check = FALSE
  ),
  modules = list(tm_g_barchart_simple(label = "ADAE Analysis", x = ::data_extract_spec(
    dataname = "ADSL",
    select = ::select_spec(choices = ::variable_choices(ADSL), multiple = FALSE)
  )))
)
```

Ultimately, the example uses `shiny` to launch the application:
```r
if (interactive()) shiny::shinyApp(app$ui, app$server)
```

Some of `teal.modules.clinical` modules allow specifying arguments using `teal::choices_selected` and `teal::data_extract_spec`,
e.g. `tm_t_summary`:
```r
adsl <- scda::synthetic_cdisc_data("latest")$adsl
app <- teal::init(
  data = teal::cdisc_data(teal::cdisc_dataset("ADSL", adsl, code = 'ADSL <- synthetic_cdisc_data("latest")$adsl')),
  modules = list(
    tm_t_summary(
      label = "Demographic Table",
      dataname = "ADSL",
      arm_var = ::choices_selected(choices = c("ARM", "ARMCD"), selected = "ARM"),
      summarize_vars = ::choices_selected(
        choices = c("SEX", "RACE", "BMRKR2", "EOSDY", "DCSREAS", "AGE"),
        selected = c("SEX", "RACE")
      )
    )
  )
)
if (interactive()) shiny::shinyApp(app$ui, app$server)
```

Refer to the API reference of specific modules for more examples and information what level of customization they offer.
