---
name: Release 🎈

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  docs:
    name: Pkgdown Docs 📚
    needs: release
    uses: insightsengineering/r.pkg.template/.github/workflows/pkgdown.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      default-landing-page: latest-tag
      deps-installation-method: setup-r-dependencies
      lookup-refs: |
        insightsengineering/teal
        insightsengineering/teal.transform
        insightsengineering/tern
        insightsengineering/rlistings
        insightsengineering/formatters
        insightsengineering/rtables
        insightsengineering/rtables.officer
        insightsengineering/teal.code
        insightsengineering/teal.data
        insightsengineering/teal.logger
        insightsengineering/teal.reporter
        insightsengineering/teal.widgets
        insightsengineering/teal.slice
        insightsengineering/tern.gee
        insightsengineering/tern.mmrm
        insightsengineering/nestcolor
        insightsengineering/roxy.shinylive
  validation:
    name: R Package Validation report 📃
    needs: release
    uses: insightsengineering/r.pkg.template/.github/workflows/validation.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      deps-installation-method: setup-r-dependencies
      lookup-refs: |
        insightsengineering/teal
        insightsengineering/teal.transform
        insightsengineering/tern
        insightsengineering/rlistings
        insightsengineering/formatters
        insightsengineering/rtables
        insightsengineering/rtables.officer
        insightsengineering/teal.code
        insightsengineering/teal.data
        insightsengineering/teal.logger
        insightsengineering/teal.reporter
        insightsengineering/teal.widgets
        insightsengineering/teal.slice
        insightsengineering/tern.gee
        insightsengineering/tern.mmrm
        insightsengineering/nestcolor
        insightsengineering/roxy.shinylive
  release:
    name: Create release 🎉
    uses: insightsengineering/r.pkg.template/.github/workflows/release.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
  build:
    name: Build package and reports 🎁
    needs: [release, docs]
    uses: insightsengineering/r.pkg.template/.github/workflows/build-check-install.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      additional-env-vars: |
        _R_CHECK_CRAN_INCOMING_REMOTE_=false
      additional-r-cmd-check-params: --as-cran
      enforce-note-blocklist: true
      note-blocklist: |
        checking dependencies in R code .* NOTE
        checking R code for possible problems .* NOTE
        checking examples .* NOTE
        checking Rd line widths .* NOTE
        checking top-level files .* NOTE
      unit-test-report-brand: >-
        https://raw.githubusercontent.com/insightsengineering/hex-stickers/main/thumbs/teal.png
      deps-installation-method: setup-r-dependencies
      lookup-refs: |
        insightsengineering/teal
        insightsengineering/teal.transform
        insightsengineering/tern
        insightsengineering/rlistings
        insightsengineering/formatters
        insightsengineering/rtables
        insightsengineering/rtables.officer
        insightsengineering/teal.code
        insightsengineering/teal.data
        insightsengineering/teal.logger
        insightsengineering/teal.reporter
        insightsengineering/teal.widgets
        insightsengineering/teal.slice
        insightsengineering/tern.gee
        insightsengineering/tern.mmrm
        insightsengineering/nestcolor
        insightsengineering/roxy.shinylive
  coverage:
    name: Coverage 📔
    needs: [release, docs]
    uses: insightsengineering/r.pkg.template/.github/workflows/test-coverage.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      additional-env-vars: |
        NOT_CRAN=true
      deps-installation-method: setup-r-dependencies
      lookup-refs: |
        insightsengineering/teal
        insightsengineering/teal.transform
        insightsengineering/tern
        insightsengineering/rlistings
        insightsengineering/formatters
        insightsengineering/rtables
        insightsengineering/rtables.officer
        insightsengineering/teal.code
        insightsengineering/teal.data
        insightsengineering/teal.logger
        insightsengineering/teal.reporter
        insightsengineering/teal.widgets
        insightsengineering/teal.slice
        insightsengineering/tern.gee
        insightsengineering/tern.mmrm
        insightsengineering/nestcolor
        insightsengineering/roxy.shinylive
  wasm:
    name: Build WASM packages 🧑‍🏭
    needs: release
    uses: insightsengineering/r.pkg.template/.github/workflows/wasm.yaml@main
